import { EhubDialogsSection } from "@/components/ehub/ehub-dialogs-section";

export function EhubDialogsSectionWrapper(props: any) {
  return (
    <EhubDialogsSection
      addContactsMutation={props.sequenceMutations.addContactsMutation}
      allContactsData={props.queries.allContactsData}
      countsError={props.state.countsError}
      deleteMutation={props.sequenceMutations.deleteMutation}
      deleteSequenceId={props.state.deleteSequenceId}
      editStepBody={props.state.editStepBody}
      editStepDialogOpen={props.state.editStepDialogOpen}
      editStepGuidance={props.state.editStepGuidance}
      editStepSubject={props.state.editStepSubject}
      editingStepId={props.state.editingStepId}
      followUpBody={props.state.followUpBody}
      followUpDialogOpen={props.state.followUpDialogOpen}
      followUpSubject={props.state.followUpSubject}
      handleAddToSequence={props.actions.handleAddToSequence}
      handleCancelNavigation={props.actions.handleCancelNavigation}
      handleConfirmNavigation={props.actions.handleConfirmNavigation}
      handleImport={props.actions.handleImport}
      handleSaveSettings={props.actions.handleSaveSettings}
      importMutation={props.sequenceMutations.importMutation}
      isAddToSequenceDialogOpen={props.state.isAddToSequenceDialogOpen}
      isImportDialogOpen={props.state.isImportDialogOpen}
      isTestDialogOpen={props.state.isTestDialogOpen}
      nukeCounts={props.state.nukeCounts}
      nukeDialogOpen={props.state.nukeDialogOpen}
      nukeEmailPattern={props.state.nukeEmailPattern}
      nukeTestDataMutation={props.operationsMutations.nukeTestDataMutation}
      pendingTab={props.state.pendingTab}
      replyScannnerDialogOpen={props.state.replyScannnerDialogOpen}
      scanPreviewResults={props.state.scanPreviewResults}
      scanRepliesMutation={props.operationsMutations.scanRepliesMutation}
      selectedContacts={props.state.selectedContacts}
      selectedScanEmails={props.state.selectedScanEmails}
      selectedTestEmailId={props.state.selectedTestEmailId}
      selectAllMode={props.state.selectAllMode}
      sendFollowUpMutation={props.operationsMutations.sendFollowUpMutation}
      sequences={props.queries.sequences}
      setActiveTab={props.state.setActiveTab}
      setDeleteSequenceId={props.state.setDeleteSequenceId}
      setEditStepBody={props.state.setEditStepBody}
      setEditStepDialogOpen={props.state.setEditStepDialogOpen}
      setEditStepGuidance={props.state.setEditStepGuidance}
      setEditStepSubject={props.state.setEditStepSubject}
      setFollowUpBody={props.state.setFollowUpBody}
      setFollowUpDialogOpen={props.state.setFollowUpDialogOpen}
      setFollowUpSubject={props.state.setFollowUpSubject}
      setIsAddToSequenceDialogOpen={props.state.setIsAddToSequenceDialogOpen}
      setIsImportDialogOpen={props.state.setIsImportDialogOpen}
      setIsTestDialogOpen={props.state.setIsTestDialogOpen}
      setNukeDialogOpen={props.state.setNukeDialogOpen}
      setNukeEmailPattern={props.state.setNukeEmailPattern}
      setPendingTab={props.state.setPendingTab}
      setReplyScannerDialogOpen={props.state.setReplyScannerDialogOpen}
      setScanPreviewResults={props.state.setScanPreviewResults}
      setSelectedScanEmails={props.state.setSelectedScanEmails}
      setSelectedTestEmailId={props.state.setSelectedTestEmailId}
      setSheetId={props.state.setSheetId}
      setShowNavigationWarning={props.state.setShowNavigationWarning}
      setTargetSequenceId={props.state.setTargetSequenceId}
      setTestEmail={props.state.setTestEmail}
      sheetId={props.state.sheetId}
      showNavigationWarning={props.state.showNavigationWarning}
      targetSequenceId={props.state.targetSequenceId}
      testEmail={props.state.testEmail}
      testSendMutation={props.sequenceMutations.testSendMutation}
      updateSettingsMutation={props.configMutations.updateSettingsMutation}
      updateStepTemplateMutation={props.strategyMutations.updateStepTemplateMutation}
    />
  );
}
