export const CITY_TO_TIMEZONE: Record<string, string> = {
  'New York': 'America/New_York',
  'Los Angeles': 'America/Los_Angeles',
  'Chicago': 'America/Chicago',
  'Houston': 'America/Chicago',
  'Phoenix': 'America/Phoenix',
  'Philadelphia': 'America/New_York',
  'San Antonio': 'America/Chicago',
  'San Diego': 'America/Los_Angeles',
  'Dallas': 'America/Chicago',
  'San Jose': 'America/Los_Angeles',
  'Austin': 'America/Chicago',
  'Jacksonville': 'America/New_York',
  'San Francisco': 'America/Los_Angeles',
  'Columbus': 'America/New_York',
  'Fort Worth': 'America/Chicago',
  'Charlotte': 'America/New_York',
  'Seattle': 'America/Los_Angeles',
  'Denver': 'America/Denver',
  'Washington': 'America/New_York',
  'Boston': 'America/New_York',
  'Nashville': 'America/Chicago',
  'Detroit': 'America/New_York',
  'Portland': 'America/Los_Angeles',
  'Las Vegas': 'America/Los_Angeles',
  'Miami': 'America/New_York',
  'Atlanta': 'America/New_York',
  'London': 'Europe/London',
  'Paris': 'Europe/Paris',
  'Berlin': 'Europe/Berlin',
  'Madrid': 'Europe/Madrid',
  'Rome': 'Europe/Rome',
  'Amsterdam': 'Europe/Amsterdam',
  'Brussels': 'Europe/Brussels',
  'Vienna': 'Europe/Vienna',
  'Warsaw': 'Europe/Warsaw',
  'Budapest': 'Europe/Budapest',
  'Prague': 'Europe/Prague',
  'Stockholm': 'Europe/Stockholm',
  'Oslo': 'Europe/Oslo',
  'Copenhagen': 'Europe/Copenhagen',
  'Dublin': 'Europe/Dublin',
  'Lisbon': 'Europe/Lisbon',
  'Athens': 'Europe/Athens',
  'Istanbul': 'Europe/Istanbul',
  'Moscow': 'Europe/Moscow',
  'Tokyo': 'Asia/Tokyo',
  'Shanghai': 'Asia/Shanghai',
  'Beijing': 'Asia/Shanghai',
  'Singapore': 'Asia/Singapore',
  'Hong Kong': 'Asia/Hong_Kong',
  'Dubai': 'Asia/Dubai',
  'Mumbai': 'Asia/Kolkata',
  'Delhi': 'Asia/Kolkata',
  'Bangalore': 'Asia/Kolkata',
  'Seoul': 'Asia/Seoul',
  'Bangkok': 'Asia/Bangkok',
  'Manila': 'Asia/Manila',
  'Toronto': 'America/Toronto',
  'Montreal': 'America/Toronto',
  'Vancouver': 'America/Vancouver',
  'Sydney': 'Australia/Sydney',
  'Melbourne': 'Australia/Sydney',
  'Auckland': 'Pacific/Auckland',
  'Mexico City': 'America/Mexico_City',
};
