import type { TimezoneData } from './types';

export const TIMEZONE_DATA: TimezoneData[] = [
  { value: 'America/New_York', label: 'Eastern Time (ET)', country: 'United States', searchTerms: ['EST', 'EDT', 'New York', 'NY', 'Eastern', 'Miami', 'Boston', 'Philadelphia', 'Washington DC', 'Atlanta'] },
  { value: 'America/Chicago', label: 'Central Time (CT)', country: 'United States', searchTerms: ['CST', 'CDT', 'Chicago', 'IL', 'Central', 'Dallas', 'Houston', 'Austin', 'Minneapolis', 'San Antonio'] },
  { value: 'America/Denver', label: 'Mountain Time (MT)', country: 'United States', searchTerms: ['MST', 'MDT', 'Denver', 'CO', 'Mountain', 'Phoenix', 'Salt Lake City', 'Albuquerque', 'Colorado'] },
  { value: 'America/Phoenix', label: 'Mountain Time - Arizona (no DST)', country: 'United States', searchTerms: ['MST', 'Phoenix', 'AZ', 'Arizona', 'Tucson', 'Mesa', 'Scottsdale'] },
  { value: 'America/Los_Angeles', label: 'Pacific Time (PT)', country: 'United States', searchTerms: ['PST', 'PDT', 'Los Angeles', 'CA', 'Pacific', 'San Francisco', 'Seattle', 'San Diego', 'Portland', 'Las Vegas'] },
  { value: 'America/Anchorage', label: 'Alaska Time (AKT)', country: 'United States', searchTerms: ['AKST', 'AKDT', 'Alaska', 'AK', 'Anchorage', 'Juneau'] },
  { value: 'Pacific/Honolulu', label: 'Hawaii-Aleutian Time (HST)', country: 'United States', searchTerms: ['HST', 'Hawaii', 'HI', 'Honolulu', 'Maui', 'Kauai'] },
  { value: 'Europe/London', label: 'British Time (GMT/BST)', country: 'United Kingdom', searchTerms: ['GMT', 'BST', 'London', 'UK', 'Britain', 'England', 'Scotland', 'Wales'] },
  { value: 'Europe/Paris', label: 'Central European Time', country: 'France', searchTerms: ['CET', 'CEST', 'Paris', 'France', 'Berlin', 'Madrid', 'Rome', 'Brussels'] },
  { value: 'Europe/Berlin', label: 'Central European Time', country: 'Germany', searchTerms: ['CET', 'CEST', 'Berlin', 'Germany', 'Munich', 'Frankfurt', 'Hamburg'] },
  { value: 'Europe/Warsaw', label: 'Central European Time', country: 'Poland', searchTerms: ['CET', 'CEST', 'Warsaw', 'Poland', 'Krakow', 'Gdansk', 'Wroclaw'] },
  { value: 'Europe/Rome', label: 'Central European Time', country: 'Italy', searchTerms: ['CET', 'CEST', 'Rome', 'Italy', 'Milan', 'Naples', 'Venice', 'Florence'] },
  { value: 'Europe/Madrid', label: 'Central European Time', country: 'Spain', searchTerms: ['CET', 'CEST', 'Madrid', 'Spain', 'Barcelona', 'Valencia', 'Seville'] },
  { value: 'Europe/Amsterdam', label: 'Central European Time', country: 'Netherlands', searchTerms: ['CET', 'CEST', 'Amsterdam', 'Netherlands', 'Rotterdam', 'The Hague'] },
  { value: 'Europe/Brussels', label: 'Central European Time', country: 'Belgium', searchTerms: ['CET', 'CEST', 'Brussels', 'Belgium', 'Antwerp', 'Bruges'] },
  { value: 'Europe/Athens', label: 'Eastern European Time', country: 'Greece', searchTerms: ['EET', 'EEST', 'Athens', 'Greece'] },
  { value: 'Europe/Istanbul', label: 'Turkey Time', country: 'Turkey', searchTerms: ['TRT', 'Istanbul', 'Turkey', 'Ankara'] },
  { value: 'Europe/Moscow', label: 'Moscow Standard Time', country: 'Russia', searchTerms: ['MSK', 'Moscow', 'Russia'] },
  { value: 'Asia/Dubai', label: 'Gulf Standard Time', country: 'UAE', searchTerms: ['GST', 'Dubai', 'UAE', 'Abu Dhabi'] },
  { value: 'Asia/Kolkata', label: 'India Standard Time', country: 'India', searchTerms: ['IST', 'India', 'Mumbai', 'Delhi', 'Bangalore', 'Kolkata', 'Chennai'] },
  { value: 'Asia/Shanghai', label: 'China Standard Time', country: 'China', searchTerms: ['CST', 'China', 'Shanghai', 'Beijing', 'Shenzhen', 'Guangzhou'] },
  { value: 'Asia/Tokyo', label: 'Japan Standard Time', country: 'Japan', searchTerms: ['JST', 'Japan', 'Tokyo', 'Osaka', 'Kyoto'] },
  { value: 'Asia/Seoul', label: 'Korea Standard Time', country: 'South Korea', searchTerms: ['KST', 'Korea', 'Seoul', 'Busan'] },
  { value: 'Asia/Singapore', label: 'Singapore Time', country: 'Singapore', searchTerms: ['SGT', 'Singapore'] },
  { value: 'Asia/Hong_Kong', label: 'Hong Kong Time', country: 'Hong Kong', searchTerms: ['HKT', 'Hong Kong'] },
  { value: 'Australia/Sydney', label: 'Australian Eastern Time', country: 'Australia', searchTerms: ['AEST', 'AEDT', 'Sydney', 'Australia', 'Melbourne', 'Brisbane'] },
  { value: 'Australia/Perth', label: 'Australian Western Time', country: 'Australia', searchTerms: ['AWST', 'Perth', 'Western Australia'] },
  { value: 'Pacific/Auckland', label: 'New Zealand Time', country: 'New Zealand', searchTerms: ['NZST', 'NZDT', 'Auckland', 'New Zealand', 'Wellington'] },
  { value: 'America/Toronto', label: 'Eastern Time (Canada)', country: 'Canada', searchTerms: ['EST', 'EDT', 'Toronto', 'Canada', 'Ottawa', 'Montreal'] },
  { value: 'America/Vancouver', label: 'Pacific Time (Canada)', country: 'Canada', searchTerms: ['PST', 'PDT', 'Vancouver', 'Canada', 'British Columbia'] },
  { value: 'America/Mexico_City', label: 'Central Time (Mexico)', country: 'Mexico', searchTerms: ['CST', 'CDT', 'Mexico City', 'Mexico'] },
  { value: 'America/Sao_Paulo', label: 'Brasilia Time', country: 'Brazil', searchTerms: ['BRT', 'BRST', 'Sao Paulo', 'Brazil', 'Rio de Janeiro'] },
  { value: 'America/Buenos_Aires', label: 'Argentina Time', country: 'Argentina', searchTerms: ['ART', 'Buenos Aires', 'Argentina'] }
];
