export const US_STATE_TO_TIMEZONE: Record<string, string> = {
  'AL': 'America/Chicago', 'Alabama': 'America/Chicago',
  'AK': 'America/Anchorage', 'Alaska': 'America/Anchorage',
  'AZ': 'America/Phoenix', 'Arizona': 'America/Phoenix',
  'AR': 'America/Chicago', 'Arkansas': 'America/Chicago',
  'CA': 'America/Los_Angeles', 'California': 'America/Los_Angeles',
  'CO': 'America/Denver', 'Colorado': 'America/Denver',
  'CT': 'America/New_York', 'Connecticut': 'America/New_York',
  'DE': 'America/New_York', 'Delaware': 'America/New_York',
  'FL': 'America/New_York', 'Florida': 'America/New_York',
  'GA': 'America/New_York', 'Georgia': 'America/New_York',
  'HI': 'Pacific/Honolulu', 'Hawaii': 'Pacific/Honolulu',
  'ID': 'America/Denver', 'Idaho': 'America/Denver',
  'IL': 'America/Chicago', 'Illinois': 'America/Chicago',
  'IN': 'America/New_York', 'Indiana': 'America/New_York',
  'IA': 'America/Chicago', 'Iowa': 'America/Chicago',
  'KS': 'America/Chicago', 'Kansas': 'America/Chicago',
  'KY': 'America/New_York', 'Kentucky': 'America/New_York',
  'LA': 'America/Chicago', 'Louisiana': 'America/Chicago',
  'ME': 'America/New_York', 'Maine': 'America/New_York',
  'MD': 'America/New_York', 'Maryland': 'America/New_York',
  'MA': 'America/New_York', 'Massachusetts': 'America/New_York',
  'MI': 'America/New_York', 'Michigan': 'America/New_York',
  'MN': 'America/Chicago', 'Minnesota': 'America/Chicago',
  'MS': 'America/Chicago', 'Mississippi': 'America/Chicago',
  'MO': 'America/Chicago', 'Missouri': 'America/Chicago',
  'MT': 'America/Denver', 'Montana': 'America/Denver',
  'NE': 'America/Chicago', 'Nebraska': 'America/Chicago',
  'NV': 'America/Los_Angeles', 'Nevada': 'America/Los_Angeles',
  'NH': 'America/New_York', 'New Hampshire': 'America/New_York',
  'NJ': 'America/New_York', 'New Jersey': 'America/New_York',
  'NM': 'America/Denver', 'New Mexico': 'America/Denver',
  'NY': 'America/New_York', 'New York': 'America/New_York',
  'NC': 'America/New_York', 'North Carolina': 'America/New_York',
  'ND': 'America/Chicago', 'North Dakota': 'America/Chicago',
  'OH': 'America/New_York', 'Ohio': 'America/New_York',
  'OK': 'America/Chicago', 'Oklahoma': 'America/Chicago',
  'OR': 'America/Los_Angeles', 'Oregon': 'America/Los_Angeles',
  'PA': 'America/New_York', 'Pennsylvania': 'America/New_York',
  'RI': 'America/New_York', 'Rhode Island': 'America/New_York',
  'SC': 'America/New_York', 'South Carolina': 'America/New_York',
  'SD': 'America/Chicago', 'South Dakota': 'America/Chicago',
  'TN': 'America/Chicago', 'Tennessee': 'America/Chicago',
  'TX': 'America/Chicago', 'Texas': 'America/Chicago',
  'UT': 'America/Denver', 'Utah': 'America/Denver',
  'VT': 'America/New_York', 'Vermont': 'America/New_York',
  'VA': 'America/New_York', 'Virginia': 'America/New_York',
  'WA': 'America/Los_Angeles', 'Washington': 'America/Los_Angeles',
  'WV': 'America/New_York', 'West Virginia': 'America/New_York',
  'WI': 'America/Chicago', 'Wisconsin': 'America/Chicago',
  'WY': 'America/Denver', 'Wyoming': 'America/Denver',
};
