import type { Conversation } from "@shared/schema";
import { InlineAiChatMainLayout } from "@/components/inline-ai-chat-main-layout";
import { InlineAiPrimaryDialogs } from "@/components/inline-ai-primary-dialogs";
import { InlineAiTemplateBuilderDialog } from "@/components/inline-ai-template-builder-dialog";

export function InlineAiChatRender(props: any) {
  return (
    <div className="flex h-full overflow-hidden">
      <InlineAiChatMainLayout
        conversations={props.conversations}
        conversationsByProject={props.conversationsByProject as Record<string, Conversation[]>}
        conversationsOpen={props.conversationsOpen}
        createConversationMutation={props.createConversationMutation}
        deleteConversationMutation={props.deleteConversationMutation}
        deleteProjectMutation={props.deleteProjectMutation}
        deleteTemplateMutation={props.deleteTemplateMutation}
        filteredTemplates={props.filteredTemplates}
        handleConversationsToggle={props.handleConversationsToggle}
        handleCopyTemplate={props.handleCopyTemplate}
        handleEditTemplateFromLibrary={props.handleEditTemplateFromLibrary}
        handleEmailTemplate={props.handleEmailTemplate}
        handleInjectTemplate={props.handleInjectTemplate}
        handleKeyPress={props.handleKeyPress}
        handleOpenTemplateBuilderFromSidebar={props.handleOpenTemplateBuilderFromSidebar}
        handleRetryMessage={props.handleRetryMessage}
        handleSendMessage={props.handleSendMessage}
        handleTemplatesToggle={props.handleTemplatesToggle}
        isSending={props.isSending}
        mergedTimeline={props.mergedTimeline}
        messageInput={props.messageInput}
        messagesLoading={props.messagesLoading}
        moveConversationMutation={props.moveConversationMutation}
        projects={props.projects}
        scrollBottomRef={props.scrollBottomRef}
        scrollRef={props.scrollRef}
        selectedConversation={props.selectedConversation}
        selectedConversationId={props.selectedConversationId}
        setMessageInput={props.setMessageInput}
        setNewConversationTitle={props.setNewConversationTitle}
        setNewProjectDialogOpen={props.setNewProjectDialogOpen}
        setRenameDialogOpen={props.setRenameDialogOpen}
        setRenamingConversationId={props.setRenamingConversationId}
        setSelectedConversationId={props.setSelectedConversationId}
        setSidebarOpen={props.setSidebarOpen}
        setTemplateBuilderOpen={props.setTemplateBuilderOpen}
        setTemplateSearch={props.setTemplateSearch}
        setTimeline={props.setTimeline}
        sidebarOpen={props.sidebarOpen}
        storeContext={props.storeContext}
        templateSearch={props.templateSearch}
        templates={props.templates}
        templatesOpen={props.templatesOpen}
        timeline={props.timeline}
        toast={props.toast}
        user={props.user}
        copyMessageToClipboard={props.copyMessageToClipboard}
        makeTemplateFromMessage={props.makeTemplateFromMessage}
        onConversationsToggle={props.handleConversationsToggle}
        onNewProject={() => props.setNewProjectDialogOpen(true)}
        onRenameConversation={(conversation: Conversation) => {
          props.setRenamingConversationId(conversation.id);
          props.setNewConversationTitle(conversation.title);
          props.setRenameDialogOpen(true);
        }}
        onSelectConversation={props.setSelectedConversationId}
        onTemplatesToggle={props.handleTemplatesToggle}
      />

      <InlineAiPrimaryDialogs
        createProjectMutation={props.createProjectMutation}
        newConversationTitle={props.newConversationTitle}
        newProjectDialogOpen={props.newProjectDialogOpen}
        newProjectName={props.newProjectName}
        previewTemplate={props.previewTemplate}
        renameConversationMutation={props.renameConversationMutation}
        renameDialogOpen={props.renameDialogOpen}
        renamingConversationId={props.renamingConversationId}
        setNewConversationTitle={props.setNewConversationTitle}
        setNewProjectDialogOpen={props.setNewProjectDialogOpen}
        setNewProjectName={props.setNewProjectName}
        setRenameDialogOpen={props.setRenameDialogOpen}
        setRenamingConversationId={props.setRenamingConversationId}
        setTemplatePreviewOpen={props.setTemplatePreviewOpen}
        storeContext={props.storeContext}
        templatePreviewOpen={props.templatePreviewOpen}
        toast={props.toast}
        user={props.user}
      />

      <InlineAiTemplateBuilderDialog
        availableVariables={props.availableVariables}
        builderContent={props.builderContent}
        builderIsDefault={props.builderIsDefault}
        builderTags={props.builderTags}
        builderTitle={props.builderTitle}
        builderType={props.builderType}
        contentTextareaRef={props.contentTextareaRef}
        convertToDirectImageUrl={props.convertToDirectImageUrl}
        createTemplateMutation={props.createTemplateMutation}
        deleteImageMutation={props.deleteImageMutation}
        deleteTagsMutation={props.deleteTagsMutation}
        deleteTemplateMutation={props.deleteTemplateMutation}
        editingTemplateId={props.editingTemplateId}
        emailBody={props.emailBody}
        emailBodyRef={props.emailBodyRef}
        emailSubject={props.emailSubject}
        emailSubjectRef={props.emailSubjectRef}
        emailTo={props.emailTo}
        emailToRef={props.emailToRef}
        extractGoogleDriveFileId={props.extractGoogleDriveFileId}
        formatEmailTemplate={props.formatEmailTemplate}
        handleDeleteSelectedTags={props.handleDeleteSelectedTags}
        handleEditTemplateFromLibrary={props.handleEditTemplateFromLibrary}
        handleImageError={props.handleImageError}
        handleTemplateTypeChange={props.handleTemplateTypeChange}
        imagePreviewError={props.imagePreviewError}
        insertImageAtCursor={props.insertImageAtCursor}
        insertTag={props.insertTag}
        insertVariable={props.insertVariable}
        newImageLabel={props.newImageLabel}
        newImageUrl={props.newImageUrl}
        saveImageMutation={props.saveImageMutation}
        savedEmailImages={props.savedEmailImages}
        selectedTagFilter={props.selectedTagFilter}
        selectedTagIds={props.selectedTagIds}
        selectedTypeFilter={props.selectedTypeFilter}
        setBuilderContent={props.setBuilderContent}
        setBuilderIsDefault={props.setBuilderIsDefault}
        setBuilderTags={props.setBuilderTags}
        setBuilderTitle={props.setBuilderTitle}
        setBuilderType={props.setBuilderType}
        setEditingTemplateId={props.setEditingTemplateId}
        setEmailBody={props.setEmailBody}
        setEmailSubject={props.setEmailSubject}
        setEmailTo={props.setEmailTo}
        setImagePreviewError={props.setImagePreviewError}
        setNewImageLabel={props.setNewImageLabel}
        setNewImageUrl={props.setNewImageUrl}
        setSelectedTagFilter={props.setSelectedTagFilter}
        setSelectedTagIds={props.setSelectedTagIds}
        setSelectedTypeFilter={props.setSelectedTypeFilter}
        setTagEditMode={props.setTagEditMode}
        setTemplateBuilderOpen={props.setTemplateBuilderOpen}
        setTemplateBuilderView={props.setTemplateBuilderView}
        setTemplateSearch={props.setTemplateSearch}
        tagEditMode={props.tagEditMode}
        templateBuilderOpen={props.templateBuilderOpen}
        templateBuilderView={props.templateBuilderView}
        templateSearch={props.templateSearch}
        templates={props.templates}
        toggleTagSelection={props.toggleTagSelection}
        updateTemplateMutation={props.updateTemplateMutation}
        useTemplate={props.useTemplate}
        userTags={props.userTags}
      />
    </div>
  );
}
