ALTER TABLE qualification_leads
ADD COLUMN IF NOT EXISTS google_maps_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS latitude NUMERIC(10,7),
ADD COLUMN IF NOT EXISTS longitude NUMERIC(11,7),
ADD COLUMN IF NOT EXISTS business_status VARCHAR(50),
ADD COLUMN IF NOT EXISTS business_hours TEXT;
